config/routes.rb
Listabeta::Application.routes.draw do
  devise_for :startups, controllers: { registrations: "startups/registrations" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'pages#home'

  get 'mercados/(:tag)' => 'pages#markets', as: :markets
  get 'dashboard' => 'pages#dashboard', as: :dashboard
  get 'pack' => 'startup_pack#pack', as: :pack
  get 'pack/confirm' => 'startup_pack#confirm', as: :confirmation
  get 'pack/confirmed' => 'startup_pack#confirmed', as: :confirmed_pack

  post 'pack/confirm/dispatch_email' => 'startup_pack#dispatch_email', as: :dispatch_email
  resources :startups do
    resources :questionnaires, only: [:new, :create]
  end

end

app/models/startup.rb
class Startup < ActiveRecord::Base
  extend FriendlyId
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  friendly_id :name, use: :slugged

  acts_as_ordered_taggable
  acts_as_ordered_taggable_on :markets

  has_enumeration_for :status, create_helpers: true
  has_enumeration_for :phase, create_helpers: true

  has_many :questionnaires, dependent: :destroy

  mount_uploader :screenshot, ScreenshotUploader

  validates :email, :name, :website, :pitch, :description, :screenshot, :phase, :state, :city, :market_list,
            presence: true
  validates :website, url: true

  scope :highlighteds, -> { where(highlighted: true, status: Status::APPROVED) }
  scope :unhighlighteds, -> { where(highlighted: false, status: Status::APPROVED) }
  scope :approvateds, -> { where(status: Status::APPROVED) }
  scope :unapprovateds, -> { where(status: Status::UNAPPROVED) }
  scope :order_by_approves, -> { order("approved_at DESC") }
  scope :order_by_highlighted_at, -> { order ("highlighted_at DESC")}

  def highlight!
    self.highlighted = true
    self.highlighted_at = DateTime.now
    save
  end

  def unhighlight!
    update_column(:highlighted, false) and save
  end

  def approve!
    return if status.eql?(Status::APPROVED)
    self.status = Status::APPROVED
    self.approved_at = DateTime.now
    StartupMailer.notify_approvation(self).deliver if save
  end

  def unapprove!
    self.status = Status::UNAPPROVED
    self.approved_at = nil
    StartupMailer.notify_unapprovation(self).deliver if save
  end
end

app/controllers/startups/registrations_controller.rb
class Startups::RegistrationsController < Devise::RegistrationsController
  def create
    build_resource(sign_up_params)

    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :sign_up if is_navigational_format?
        sign_up(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end
  
  protected

  def after_sign_up_path_for(resource)
    root_path
  end
end

app/controllers/startups_controller.rb
class StartupsController < InheritedResources::Base
  def index
    @startups = Startup.approvateds.order_by_approves.page(params[:page]).per(15)
  end

  def show
    if resource.status.eql?(2)
      show!
    else
      redirect_to root_path, notice: 'Essa startup ainda não está disponível.'
    end
  end

  private

  def resource
    @startup ||= Startup.friendly.find(params[:id])
  end
end

app/views/startups/_startup_box.html.slim
.startup-box
  .image-area
    = link_to startup_path(startup) do
      = image_tag startup.screenshot_url, class: 'img-responsive'
  .description
    = link_to startup.name, startup_path(startup), class: 'title'
    p = truncate(startup.pitch, length: 120)

app/views/startups/_startup_box_big.html.slim
.startup-box-big
  .image-area
    = link_to startup_path(startup) do
      = image_tag startup.screenshot_url, class: 'img-responsive'
  .description
    = link_to startup.name, startup_path(startup), class: 'title'
    p 
      i = truncate(startup.pitch, length: 160)
    p = truncate(startup.description, length: 400)

app/views/startups/index.html.slim
- set_meta_tags :site => "LISTABETA | Startups", :keywords => 'Todas as Startups, Startups, Lista, Beta, Lista Beta, LISTABETA, Lista de Startups, Lançamentos de Startups', :og => { :description => 'Fique por dentro dos últimos lançamentos de Startups', :title => "LISTABETA | Startups", :image => "#{image_url('logo-azul.png')}", :url =>request.url }

.container
  .row-fluid
    .text-center
      p.show-title Startups
      p.show-pitch Confira as últimas startups lançadas
    .col-md-10.col-sm-12.col-md-offset-1
      - @startups.each do |startup|
        .col-md-4.col-sm-4
          = render partial: 'startups/startup_box', locals: {startup: startup}

.text-center
  = paginate collection

= render partial: 'layouts/newsletter'

app/views/startups/show.html.slim
- set_meta_tags :site => "LISTABETA | #{resource.name}", :keywords => resource.market_list.join(', '), :og => { :description => resource.pitch, :title => "LISTABETA| #{resource.name}", :image => resource.screenshot_url, :url => request.url }

.show-page
  .container
    .row-fluid
      .col-md-10.col-sm-12.col-md-offset-1
        p.show-title.text-center = resource.name
        p.show-pitch.text-center = resource.pitch
        .img-startup
          .img-startup-frame
            .row-fluid
              .img-startup-bar
                .col-md-1.col-sm-1
                  .img-startup-bar-circle.red
                  .img-startup-bar-circle.yellow
                  .img-startup-bar-circle.green
                .col-md-10.col-sm-10.col-md-offset-1.col-sm-offset-1
                  .img-startup-bar-input
            .row-fluid
              .img-startup-site
                = image_tag resource.screenshot, width: "100%", class: 'img-responsive'
          .cold-md-8.col-sm-8.col-md-offset-2.col-sm-offset-2.text-center
            - resource.tag_counts_on(:markets).each do |f|
              span.label.label-default.market-tag
                = link_to "#{f.name} (#{f.count})", markets_path(f.name.downcase.gsub(' ', '-'))
        .col-md-8.col-sm-8.col-md-offset-2.col-sm-offset-2
          .startup-pitch
            = resource.description
          .startup-btns.text-center
            = link_to "VISITE O SITE", resource.website, target: "_blank", class: 'btn default-btn fade visit'
            .btn-group
              button.btn.dropdown-toggle.default-btn.fade.share type="button" data-toggle="dropdown"
                | COMPARTILHE
                span.caret
              ul.dropdown-menu role="menu"
                li
                  = link_to "Facebook", "https://www.facebook.com/sharer/sharer.php?u=#{Rack::Utils.escape(request.url)}", target: "_blank"
                li
                  = link_to "Twitter", "https://twitter.com/share?url=#{request.url}&hashtags=listabeta&text=#{truncate(resource.name, length: 30, omission: '...')}%20-&via=LISTABETAbr", target: "_blank"
            = link_to "DÊ O SEU FEEDBACK", new_startup_questionnaire_url(resource), target: "_self", class: 'btn default-btn fade feedback'

= render partial: 'layouts/newsletter'