config/routes.rb
Listabeta::Application.routes.draw do
  devise_for :startups, controllers: { registrations: "startups/registrations" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'pages#home'

  get 'mercados/(:tag)' => 'pages#markets', as: :markets
  get 'dashboard' => 'pages#dashboard', as: :dashboard
  get 'pack' => 'startup_pack#pack', as: :pack
  get 'pack/confirm' => 'startup_pack#confirm', as: :confirmation
  get 'pack/confirmed' => 'startup_pack#confirmed', as: :confirmed_pack

  post 'pack/confirm/dispatch_email' => 'startup_pack#dispatch_email', as: :dispatch_email
  resources :startups do
    resources :questionnaires, only: [:new, :create]
  end

end

app/views/pages/dashboard.html.slim
.container.dashboard
  .col-md-12.text-center.col-sm-12
    h1 = "Dashboard <b>#{current_startup.name}</b>".html_safe
    .register
      .form-group
        .col-md-6.text-center.col-sm-6.col-md-offset-3.col-sm-offset-3
          | Link para o formulário de Feedback
        .col-md-6.text-center.col-sm-6.col-md-offset-3.col-sm-offset-3
          = text_field_tag nil, new_startup_questionnaire_url(current_startup), class: 'form-control text-center', readonly: true

  - if @feedbacks_total.zero?
    .col-md-6.text-center.col-sm-6.col-md-offset-3.col-sm-offset-3
      h3 Você ainda não recebeu nenhum feedback.
      p = "Enquanto isso, que tal publicar ou ler algumas notícias no #{link_to 'STARTUPNEWS', 'http://www.startupnews.com.br', target: 'blank'}".html_safe
  - else
    br
    br
    .container
      .col-md-4.col-sm-4.text-center
        .feedback-counter
          = @feedbacks_total
        .feed-detail TOTAL DE FEEDBACKS
      
      .col-md-8.col-sm-8
        = line_chart @count_last_seven_days_for
      br
      br
    .container
      .col-md-12.col-sm-12.text-center
        .col-md-6.col-sm-6
          h4 = t('activerecord.attributes.questionnaire.a2')
          = pie_chart @a2, height: "150px"
        .col-md-6.col-sm-6
          h4 = t('activerecord.attributes.questionnaire.a3')
          = pie_chart @a3, height: "150px"
        .col-md-6.col-sm-6
          h4 = t('activerecord.attributes.questionnaire.a4')
          = pie_chart @a4, height: "150px"
        .col-md-6.col-sm-6
          h4 = t('activerecord.attributes.questionnaire.a5')
          = pie_chart @a5, height: "150px"

    hr
    .container
      .col-md-12.col-sm-12
        ul#myTab.nav.nav-tabs
          li.active
            a data-toggle="tab" href="#home" PITCH
          li
            a data-toggle="tab" href="#profile" Opiniões
          li
            a data-toggle="tab" href="#messages" Lista de emails
        .tab-content
          #home.tab-pane.active
            h1 Últimas opiniões sobre o PITCH
            table.table.table-striped
              thead
                th
              tbody
                - @all_questionnaires.each do |questionnaire|
                  tr
                    td = questionnaire.a1
          
          #profile.tab-pane
            h1 Últimas opiniões para sua Startup
            table.table.table-striped
              thead
                th
              tbody
                - @all_questionnaires.each do |questionnaire|
                  tr
                    td = questionnaire.opinion
          
          #messages.tab-pane
            h1 Lista de Early Adopters
            table.table.table-striped
              thead
                th
              tbody
                - @all_questionnaires.page(params[:page]).per(20).each do |questionnaire|
                  tr
                    td
                      = link_to questionnaire.email, '#', data: { toggle: "modal", target: "#modal-#{questionnaire.id}" }

                      .modal.fade.in role="dialog" id="modal-#{questionnaire.id}" aria-hidden="false"
                        .modal-dialog
                          .modal-content
                            .modal-header
                              button type="button" class="close" data-dismiss="modal" aria-hidden="true"&times;
                              h2.modal-title = questionnaire.email
                            .modal-body
                                span.label.label-info = t('activerecord.attributes.questionnaire.a1')  
                                p = questionnaire.a1

                                span.label.label-info = t('activerecord.attributes.questionnaire.a2')
                                p = questionnaire.a2_humanize

                                span.label.label-info = t('activerecord.attributes.questionnaire.a3')
                                p = questionnaire.a3_humanize

                                span.label.label-info = t('activerecord.attributes.questionnaire.a4')
                                p = questionnaire.a4_humanize

                                span.label.label-info = t('activerecord.attributes.questionnaire.a5')
                                p = questionnaire.a5_humanize

                                span.label.label-info = t('activerecord.attributes.questionnaire.opinion')
                                p = questionnaire.opinion

                            .modal-footer
                              button.btn.btn-default data-dismiss="modal" type="button" Fechar

                .text-center
                  = paginate @all_questionnaires.page(params[:page]).per(20)


javascript:
  $('#myTab a').click(function (e) {
    e.preventDefault()
    $(this).tab('show')
  })
  
  // $('a.showFeedback').click(function (e) {
  //   console.log('clicou')
  //   $('#showFeedback').modal('toggle')
  // })

app/views/pages/home.html.slim
- set_meta_tags :site => "LISTABETA", :keywords => 'Startups, Lista, Beta, Lista Beta, Lista de Startups, Lançamentos de Startups, LISTABETA', :og => { :description => 'Confira os últimos lançamentos sobre Startups do Brasil.', :title => "LISTABETA", :image => "#{image_url('logo-azul.png')}", :url => "#{request.url}" }
.promo-message
  span Aprenda na prática a desenvolver seu potencial, formando sua equipe e criando sua startup. #{link_to "Saiba mais", "http://www.colisoes.com.br", target: "_blank"}.

.banner
  .container.text-center
    h1 Se você não pode ser encontrado, você não existe
    h3 Tenha acesso exclusivo as mais novas startups brasileiras
    .col-md-8.col-sm-12.col-md-offset-3
      .col-md-3.col-sm-4.icon-header
        = image_tag 'icon-envie.png', title: 'Envie sua Startup'
        br/
        | ENVIE SUA STARTUP
      .col-md-3.col-sm-4.icon-header
        = image_tag 'icon-email.png', title: 'Early adopters recebem por email'
        br/
        | EARLY ADOPTERS RECEBEM POR EMAIL
      .col-md-3.col-sm-4.icon-header
        icon-header
        = image_tag 'icon-feedback.png', title: 'Ganhe usuários e feedback'
        br/
        | GANHE USUÁRIOS E FEEDBACK

= render partial: 'layouts/newsletter'

.container
  .row-fluid
    .text-center
      p.subtitle Novas Startups
    .col-md-10.col-sm-12.col-md-offset-1
      - @unhighlighteds.each do |startup|
        .col-md-4.col-sm-4
          = render partial: 'startups/startup_box', locals: {startup: startup}
      .text-center
        .clearfix
        = link_to "MAIS STARTUPS", startups_path, class: 'btn default-btn fade'

      .text-center
        p.subtitle Mercados em Destaque
        .tag-cloud.text-center
          - @all_markets.each do |f|
            span.label.label-default.market-tag
              = link_to "#{f.name} (#{f.count})", markets_path(f.name.downcase.gsub(' ', '-'))

        = link_to "TODOS MERCADOS", markets_path, class: 'btn default-btn fade'
      br
      br
      br
    .text-center
      p.subtitle Startups em Destaque
    .col-md-8.col-sm-12.col-md-offset-2
      - @highlighteds.each do |startup|
        = render partial: 'startups/startup_box_big', locals: {startup: startup}

= render partial: 'layouts/press'

app/views/pages/markets.html.slim
- set_meta_tags :site => "LISTABETA | Mercados", :keywords => 'Startups, Lista, Beta, Lista Beta, LISTABETA, Mercados, Lista de Startups, Lançamentos de Startups', :og => { :description => 'Todas as Startups classificadas pelos principais tipos de mercados.', :title => "LISTABETA | Mercados", :image => "#{image_url('logo-azul.png')}", :url => request.url }

.container
  .boxes-area
    - if @startups.present?
      .text-center
        p.subtitle = "Startups em <b>#{params[:tag]}</b>".html_safe
      - @startups.each do |startup|
        = render partial: 'startups/startup_box', locals: {startup: startup}
      .clearfix
      .text-center
        = link_to "OUTRAS STARTUPS", startups_path, class: 'btn default-btn fade'
      br/

    - elsif @markets.present?
      .text-center
        p.subtitle Mercados
        .tag-cloud
          - @markets.each do |f|
            span.label.label-default.market-tag = link_to "#{f.name} (#{f.count})", markets_path(f.name.downcase.gsub(' ', '-'))
      br/

= render partial: 'layouts/newsletter'