config/routes.rb
Listabeta::Application.routes.draw do
  devise_for :startups, controllers: { registrations: "startups/registrations" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'pages#home'

  get 'mercados/(:tag)' => 'pages#markets', as: :markets
  get 'dashboard' => 'pages#dashboard', as: :dashboard
  get 'pack' => 'startup_pack#pack', as: :pack
  get 'pack/confirm' => 'startup_pack#confirm', as: :confirmation
  get 'pack/confirmed' => 'startup_pack#confirmed', as: :confirmed_pack

  post 'pack/confirm/dispatch_email' => 'startup_pack#dispatch_email', as: :dispatch_email
  resources :startups do
    resources :questionnaires, only: [:new, :create]
  end

end

app/views/layouts/_flash.html.slim
.flash
  - for key, msg in flash
    - flash_class = key.to_s == "alert" ? "alerts-error" : key
    div class="#{flash_class} wrapper"
      div class="#{flash_class}"
        = msg

app/views/layouts/_footer.html.slim
.container
  footer
    .clearfix
    .footer-links.text-center
      = link_to "Blog", "http://blog.listabeta.com.br", target: '_blank'
      | &nbsp
      | -
      | &nbsp
      = link_to "Facebook", "https://www.facebook.com/pages/Lista-Beta/549730495106083", target: '_blank'
      | &nbsp
      | -
      | &nbsp
      = link_to "Twitter", "http://www.twitter.com/listabetabr", target: '_blank'
      | &nbsp
      | -
      | &nbsp
      = link_to "Contato", "mailto:contato@listabeta.com.br", target: '_blank'
    .container.footer-logo.text-center
      p.brand
      = link_to image_tag("logo-codeland-branco.png", alt: "Developed by CODELAND", width: "100"), 'http://www.codeland.com.br', target: 'blank'

app/views/layouts/_header.html.slim
nav.navbar.navbar-default.navbar-fixed-top.menu-wrapper[role="navigation"]
  .container
    .navbar-header
      button.navbar-toggle[data-target="#navbar-collapse" data-toggle="collapse" type="button"]
        span.sr-only Navegar
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to root_path do
        .logo
          = image_tag 'logo-azul.png', title: 'LISTABETA'

    #navbar-collapse.collapse.navbar-collapse
      ul.nav.navbar-nav
        li
          = link_to startups_path do
            .menu-item.menu-fade
              span STARTUPS
        li
          - if startup_signed_in?
            = link_to dashboard_path do
              .menu-item.menu-fade
                span DASHBOARD
          - else
            .menu-button
              = link_to "ENVIE SUA STARTUP", new_startup_registration_path, class: 'btn default-btn fade'
      ul.nav.navbar-nav.navbar-right
        li
          - if startup_signed_in?
            = link_to destroy_startup_session_path, method: :delete do
              .menu-item.last-menu-item.menu-fade
                span SAIR
          - else
            = link_to new_startup_session_path do
              .menu-item.last-menu-item.menu-fade
                span ENTRAR

app/views/layouts/_mailchimp.html.slim
form.form-inline action="http://listabeta.us3.list-manage.com/subscribe/post?u=85d2b1e556a6a9e7f59a2b1a4&amp;id=da1a8648fb" method="post" novalidate="" role="form" target="_blank"
  .form-group
    input#mce-EMAIL.form-control.pull-left name="EMAIL" placeholder="Seu email" type="email"
    button.btn.default-btn.fade.pull-right type="submit" ASSINAR

app/views/layouts/_newsletter.html.slim
.newsletter
  .container
    .row-fluid
      .col-md-10.col-sm-12.col-md-offset-1
        .row
          .col-md-8.col-sm-12
            h2 Não perca a próxima grande startup
            p.sub-header Receba em seu e-mail as últimas startups brasileiras.
          .col-md-4.col-sm-12
              = render partial: 'layouts/mailchimp'

app/views/layouts/_pack_header.html.slim
.menu-wrapper.navbar-fixed-top
  .container
    = link_to root_path do
      .pack-logo
        = image_tag 'startup_pack-logo.png', title: 'LISTABETA'

app/views/layouts/_press.html.slim
.press
  .container
    .row-fluid
      .col-md-10.col-md-offset-1
        .col-md-6.col-sm-6
          h2 LISTABETA na imprensa
          p.sub-header Confira o que estão falando sobre nós
        .col-md-3.col-sm-3.text-center
          = link_to image_tag('press-startupi-pb.png'), 'http://startups.ig.com.br/2013/vitrine-para-startups-lista-beta-da-acesso-a-empresas-no-estagio-inicial/', target: '_blank', title:'Startupi'
        .col-md-3.col-sm-3.text-center
          = link_to image_tag('press-pegn-pb.png'), 'http://revistapegn.globo.com/Noticias/noticia/2013/11/listabeta-nasce-como-uma-vitrine-online-para-startups-em-fase-inicial.html', target: '_blank', title:'Pequenas Empresas Grandes Negócios'

app/views/layouts/application.html.slim
doctype html

html
  head
    script src="https://www.google.com/jsapi" type="text/javascript"
    meta[charset="utf-8"]
    /[if lt IE 9]
      script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"
      meta[content="text/html; charset=utf-8" http-equiv="Content-Type"]
    link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application", "chartkick"
    = csrf_meta_tags
    = favicon_link_tag "favicon.ico"
    = analytics_init if Rails.env.production?

    / Dynamic Meta Tags
    = display_meta_tags
  body
    = render partial: 'layouts/flash'
    - if params[:controller].eql?('startup_pack')
      = render partial: 'layouts/pack_header'
    - else
      = render partial: 'layouts/header'
    = yield
  footer
    = render partial: 'layouts/footer'